### ISSUE TITLE
مدیریت محتوای عمومی وبسایت توسط ادمین

### ISSUE THREAD

**Issue by abarpc** [m-bassiri/Azadware#4]

**Comment by abarpc** [comment]
یعنی متن درباره ما، پشتیبانی و سایر موسسات

**Comment by m-bassiri** [comment]
طراحی جداول مورد نیاز انجام شد فقط باید سمت فرانت فرمش طراحی بشه و به دیتابیس متصل بشه
جداولش toptions و torganizations
